Algoritmo "exercicio10-lista2"
Var
valorCompra,prestacao:real



Inicio
escreval("------------------ CAIXA ------------------")
escreval("Qual o valor da compra? ")
leia(valorCompra)
prestacao<- valorCompra / 5
escreval()
escreva("O Valor de cada prestação dividida em 5x é de: ")
escreval("R$",prestacao)
escreval("------------ OPERAÇÃO FINALIZADA -----------")
         

         




Fimalgoritmo
